[package]
name = "typhoon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.30", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
rustyline = "15.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
