[package]
name = "typhoon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
rustyline = "15.0.0"
